{
  "name": "coin-backend",                // Nama Worker
  "main": "worker.js",                   // File entry-point Worker
  "compatibility_date": "2026-01-03",    // Tanggal kompatibilitas
  "kv_namespaces": [
    {
      "binding": "KV_BINDING",           // Nama variabel di Worker
      "id": "633167e54fe14122a813144aee301692"  // KV Namespace ID
    }
  ]
}
